target:
    arch: x86
    bsp: x86-qemu

partitions:
    - name: pr1
      features: [timer, libc]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]
    - name: pr2
      features: [timer, libc]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]

kernel:
    features: [debug]
    scheduler:
        policy: pps
        base_slot_length: 1s
        # Because the policy is PPS, the following configurations are unused in fact.
        major_frame: 7s
        slots:
            - partition: pr1
              duration: 1s
            - partition: pr2
              duration: 2s
            - partition: pr1
              duration: 3s
            - partition: pr2
              duration: 1s
