target:
    arch: x86
    bsp: x86-qemu

partitions:
    - name: pr1
      features: [timer, libc]
      scheduler: STATIC
      semaphores: 1
      threads:
          count: 32
          features: [sleep]
      size: 300kB
      objects: ["main.o"]

kernel:
    features: [debug]
    scheduler:
        major_frame: 10s
        slots:
            - partition: pr1
              duration: 10s
    