#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2022 POK team

target:
    arch: x86
    bsp: x86-qemu

partitions:
    - name: pr1
      features: [timer, console, libc]
      threads:
          count: 5
          features: [sleep, suspend]
      scheduler: pps
      size: 130kB
      objects: ["main.o", "activity.o"]

kernel:
    features: [debug, sched_info]
    scheduler:
        major_frame: 10s
        slots:
            - partition: pr1
              duration: 10s
