#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2022 POK team

target:
    arch: x86
    bsp: x86-qemu

partitions:
    - name: pr1
      features: [timer, libc]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]
    - name: pr2
      features: [timer, libc]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]
    - name: pr3
      features: [timer, libc]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]

kernel:
    features: [debug]
    scheduler:
        # Weight-Round-Robin example
        major_frame: 6s
        slots:
            - partition: pr1
              duration: 1s
            - partition: pr2
              duration: 3s
            - partition: pr3
              duration: 2s

        # Round-Robin example
        # major_frame: 3s
        # slots:
        #     - partition: pr1
        #       duration: 1s
        #     - partition: pr2
        #       duration: 1s
        #     - partition: pr3
        #       duration: 1s
